### ISSUE TITLE
상품 등록 시 상품 재등록 여부의 체크는 어떤 정보로 비교 하는게 좋을 가요?

### ISSUE THREAD

**Issue by HoyoungLee-B2LINK** [thdtjsdn/B2LINK_WorkSpace_JS#153]
상품 등록 시 상품 재등록 여부의 체크는 어떤 정보로 비교 하는게 좋을 가요?

1. barcode?

2. nm_kr?

3. nm_kr + brand + category ?

4. 등 등 ..

**Comment by raybirdy** [comment]
@HoyoungLee-B2LINK

barcode 와 brand_id 로   진행 하면 가능 할거라 생각해요.. (혹시 더욱더 하시고 싶으시면 nm 까지 처리 하시면 될거 같습니다. )
barcode 자체가 고유값이기 때문에 원론적으로는 하나로 끝나지만 ( 영세 업체들은 자체 제작한다고 합니다. )
추가적인 아이디어 있으시면 적용하셔도 됩니다.

**Comment by HoyoungLee-B2LINK** [comment]
프로시저에 나와있는 데로 
nm_kr
nm_cn
nm_us
url
barcode 
5개 컬럼으로 우선 실행 해보고 문제가 발생 시 대응법을 다시 찾아보겠습니다.
