### ISSUE TITLE
[MongoDB Schema] product_basic collection 에 업데이트 시간 관련 필드 추가 부탁드립니다 

### ISSUE THREAD

**Issue by HoyoungLee-B2LINK** [thdtjsdn/B2LINK_WorkSpace_JS#181]
등록 시 date_regist 가 있는 데 수정 시의 시간 관련  필드가 없어서 
요청드립니다.

**Comment by raybirdy** [comment]
@HoyoungLee-B2LINK 
수정자와 시간 관련 필드가 함께 있으면 합니다. 

modify_history : [ { "update_date" : [] , "_id$member" : id  }, { "update_date" : [] , "_id$member" : id }, ... ]

이런형태로 진행하는건 어떨까요?.. 
최종 수정자 보다는, 수정 이력을 남기는 것이 좋을 거 같아서요...

**Comment by HoyoungLee-B2LINK** [comment]
이게 좋을 거 같습니다.
